- name: Ensure SonarQube directory exists
  become: yes
  become_user: azureuser
  file:
    owner: "azureuser"
    path: "/home/azureuser/repository"
    state: directory
    mode: '0750'

- name: Install Git
  apt:
    name: git
    state: present
  when: ansible_os_family == "Debian"

- name: Clone Git Repository
  become: yes
  become_user: azureuser
  git:
    repo: "https://github.com/CMR-SID2/backend"
    dest: "/home/azureuser/repository"
    version: "main"
    force: yes
